### ISSUE TITLE
stich together drone images

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/fowlers_veg_timeline#10]

**Comment by adelegem** [comment]
done + saved in spatial drive, in fowlers_gap/adele_gemmell

**Comment by adrian-g-fisher** [comment]
You should combine the single band reflectance images made by Pix4D into a five band image. I normally do this with gdal_translate but you could use any software.

**Comment by adelegem** [comment]
okay - pretty sure this is now done and saved in fowlers_gap/adele_gemmell :')
