### ISSUE TITLE
create height model for rasters using python code

### ISSUE THREAD

**Issue by adelegem** [traitecoevo/fowlers_veg_timeline#20]

**Comment by adrian-g-fisher** [comment]
You can use two scripts in https://github.com/adrian-g-fisher/point_clouds to create the canopy height models (CHM).

1. Install Anaconda, and create a conda environment with all the required software.
- Open an Anaconda prompt, which looks like a Windows command prompt.
- Type the following to create the environment called pointclouds:
`conda config --add channels conda-forge`
`conda config --add channels rios`
`conda create -n pointclouds rios scipy numba rios::pynninterp laspy lazrs-python`

- Download the scripts lazMerge.py and droneLasProcessing.py to your PC and navigate to that directory using the change directory command, such as:
`cd C:\Users\Adrian\Documents\GitHub\point_clouds`

- Copy the LAZ files made by Pix4D (..\2_densification\point_cloud\*.laz) to your PC
- Run lazMerge.py to merge all the laz files into one.
'lazMerge.py --inDir C:\Users\Adrian\Documents\temp --outLaz C:\Users\Adrian\Documents\temp\merged.laz'
- Run droneLasProcessing.py to create a digital surface model (DSM), digital elevation model (DEM), and canopy height model (CHM).
`droneLasProcessing.py -i  C:\Users\Adrian\Documents\temp\merged.laz -e 32754 -p conservation -o C:\Users\Adrian\Documents\temp`
