### ISSUE TITLE
mEd formula??? 

### ISSUE THREAD

**Issue by adelegem** [traitecoevo/fowlers_veg_timeline#27]

**Comment by wcornwell** [comment]
```
library(tictoc)
library(parallelDist)

# Set the seed for reproducibility
set.seed(123)

# Generate a 10000x5 matrix with random numbers
random_matrix <- matrix(rnorm(10000 * 5), nrow = 10000, ncol = 5)

tic()
a<-dist(random_matrix)
toc()

tic()
b<-parDist(random_matrix)
toc()

print(all.equal(as.numeric(a), as.numeric(b), tolerance = 1e-9))
```

**Comment by wcornwell** [comment]
kinda blows out fast because this is already a 50M cell output, which is about as big as my computer can handle.  `parDist` speeds it up but doesn't solve the memory problem

**Comment by wcornwell** [comment]
any way to reduce the size of the starting matrix?   @adelegem ?

**Comment by adelegem** [comment]
i suppose we could reduce it by selecting a number of random pixels instead of using the entire matrix, but other than that i'm not sure

**Comment by wcornwell** [comment]
https://en.wikipedia.org/wiki/Medoid or
https://en.wikipedia.org/wiki/Geometric_median ? 
Need to discuss with @adrian-g-fisher

**Comment by adrian-g-fisher** [comment]
The JRSRP uses the medoid, but they implement it with some ugly fortran code, and I don't think there is much difference between them.

This python package can do both:
https://github.com/daleroberts/hdmedians

This package will implement the per pixel geometric median, and is what I have been using to make MODIS monthly median composite images:
https://github.com/daleroberts/hdstats

**Comment by wcornwell** [comment]
I think we'd have to use that to aggregate spatially so that the plots are ~10,000 pixels?  which works out to 1-m pixels.  

Just not sure if the spatial aggregation makes sense to then put into the mEd method.  Maybe it does since that was designed for big pixels anyway?

**Comment by adelegem** [comment]
too hard basket
