### ISSUE TITLE
Fractional Cover Data 

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/fowlers_veg_timeline#6]

**Comment by adrian-g-fisher** [comment]
Probably the best way to access Landsat fractional cover data is through Digital Earth Australia:
https://docs.dea.ga.gov.au/setup/Sandbox/sandbox.html

You need to program with python in a jupyter lab environment, but there are lots of example notebooks to use. You can also access the surface reflectance images from Landsat and Sentinel-2.

Andres used the data in this paper: https://doi.org/10.3390/rs14246322

There is also a repository with notebooks I made for a workshop: https://gitlab.com/jrsrp/themes/cover/aaa_awesome_cover_notebooks
