### ISSUE TITLE
previous data organizational efforts

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/fowlers_veg_timeline#8]
https://unsw-my.sharepoint.com/personal/z3165721_ad_unsw_edu_au/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fz3165721%5Fad%5Funsw%5Fedu%5Fau%2FDocuments%2FFowlers%20Gap&fromShare=true&ga=1

**Comment by adelegem** [comment]
hey @wcornwell I can't view as not shared with me - if you can get me access, my email is z5345928@ad.unsw.edu.au :)
